//
// Created by - on 23.03.2022.
//

#ifndef LEGKODUKH_MEPHI_LAB1_VARIANT22_TESTS_H
#define LEGKODUKH_MEPHI_LAB1_VARIANT22_TESTS_H

#include "Matrix.h"

#endif //LEGKODUKH_MEPHI_LAB1_VARIANT22_TESTS_H
